version: "3.8"

services:
  nginx:
    image: nginx:1.25
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - backend
    restart: always

  web:
    image: ghcr.io/quan0715/cloud-native-final-frontend:${FRONTEND_TAG:-beta}
    container_name: frontend_app
    restart: always
    depends_on:
      - backend

  backend:
    image: ${BACKEND_IMAGE_NAME}:${BACKEND_IMAGE_TAG}
    container_name: backend_app
    environment:
      MONGODB_URI: "mongodb://mongo:27017/mini-lab"
      PORT: "3000"
      JWT_SECRET: "YOUR_JWT_SECRET_HERE_OR_IN_EC2_ENV_FILE"
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: prometheus_monitoring
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    restart: always

  grafana:
    image: grafana/grafana:10.1.5
    container_name: grafana_monitoring
    ports:
      - "127.0.0.1:3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "YOUR_GRAFANA_ADMIN_PASSWORD_HERE_OR_IN_EC2_ENV_FILE"
    depends_on:
      - prometheus
    restart: always

volumes:
  mongo_data:
  prometheus_data:
  grafana_data:
