services:
  backend:
    image: ghcr.io/quan0715/cloud-native-final-backend:beta
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: "mongodb://mongo:27017/mini-lab"
      PORT: "3000"
      JWT_SECRET: "quan0715"

    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  mongo_data:
  grafana-storage:
